
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 12 12:01:37 CET 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 16;
  public static final int PEN = 13;
  public static final int LECTURER = 15;
  public static final int NUMME = 12;
  public static final int TILL = 17;
  public static final int SAY = 5;
  public static final int PERIOD = 18;
  public static final int SOME_STRING = 21;
  public static final int PROLOG = 10;
  public static final int HASKELL = 9;
  public static final int GO = 2;
  public static final int TAKE = 3;
  public static final int EOF = 0;
  public static final int ASSISTANT = 14;
  public static final int DIRECTION = 19;
  public static final int DROP = 4;
  public static final int error = 1;
  public static final int PROGP = 11;
  public static final int LABNOTES = 8;
  public static final int BOOK = 7;
  public static final int GREET = 6;
  public static final int BYEBYE = 20;
}

