
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jan 12 12:01:37 CET 2012
//----------------------------------------------------

import java.util.List;
import java_cup.runtime.*;

/** CUP v0.10k generated parser.
  * @version Thu Jan 12 12:01:37 CET 2012
  */
public class Tolk extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Tolk() {super();}

  /** Constructor which sets the default scanner. */
  public Tolk(java_cup.runtime.Scanner s) {super(s);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\031\000\002\002\004\000\002\003\004\000\002\004" +
    "\003\000\002\004\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\005\004\000" +
    "\002\006\004\000\002\007\004\000\002\011\004\000\002" +
    "\010\006\000\002\014\003\000\002\014\003\000\002\014" +
    "\003\000\002\012\004\000\002\012\004\000\002\012\003" +
    "\000\002\013\004\000\002\013\004\000\002\013\003\000" +
    "\002\016\003\000\002\016\003\000\002\015\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\047\000\016\004\020\005\006\006\005\007\013\010" +
    "\016\026\015\001\002\000\004\002\051\001\002\000\020" +
    "\011\032\012\031\013\034\014\037\015\036\016\043\017" +
    "\042\001\002\000\020\011\032\012\031\013\034\014\037" +
    "\015\036\016\043\017\042\001\002\000\004\024\ufffc\001" +
    "\002\000\004\024\uffff\001\002\000\004\024\ufffe\001\002" +
    "\000\004\024\ufffb\001\002\000\004\027\026\001\002\000" +
    "\004\024\ufffd\001\002\000\004\024\ufffa\001\002\000\006" +
    "\020\024\021\023\001\002\000\004\024\022\001\002\000" +
    "\004\025\021\001\002\000\004\024\ufff7\001\002\000\004" +
    "\002\000\001\002\000\004\024\uffeb\001\002\000\004\024" +
    "\uffea\001\002\000\004\024\ufff6\001\002\000\004\023\027" +
    "\001\002\000\006\020\024\021\023\001\002\000\004\024" +
    "\ufff5\001\002\000\004\024\uffec\001\002\000\004\024\uffef" +
    "\001\002\000\004\024\ufff4\001\002\000\004\011\047\001" +
    "\002\000\004\024\ufff2\001\002\000\004\012\046\001\002" +
    "\000\004\011\045\001\002\000\004\024\ufff9\001\002\000" +
    "\004\024\ufff3\001\002\000\004\024\uffe9\001\002\000\004" +
    "\012\044\001\002\000\004\024\uffed\001\002\000\004\024" +
    "\ufff0\001\002\000\004\024\uffee\001\002\000\004\024\ufff1" +
    "\001\002\000\004\024\ufff8\001\002\000\004\002\001\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\047\000\020\003\003\004\016\005\007\006\010\007" +
    "\013\010\006\011\011\001\001\000\002\001\001\000\012" +
    "\012\032\013\040\014\047\015\034\001\001\000\012\012" +
    "\032\013\040\014\037\015\034\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\016\024\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\016" +
    "\027\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Tolk$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Tolk$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Tolk$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Tolk$actions {
  private final Tolk parser;

  /** Constructor */
  CUP$Tolk$actions(Tolk parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Tolk$do_action(
    int                        CUP$Tolk$act_num,
    java_cup.runtime.lr_parser CUP$Tolk$parser,
    java.util.Stack            CUP$Tolk$stack,
    int                        CUP$Tolk$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Tolk$result;

      /* select the action based on the action number */
      switch (CUP$Tolk$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // pen ::= PEN 
            {
              Things RESULT = null;
		 RESULT = Things.PEN; 
              CUP$Tolk$result = new java_cup.runtime.Symbol(11/*pen*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // person ::= ASSISTANT 
            {
              People RESULT = null;
		 RESULT = People.ASSISTANT; 
              CUP$Tolk$result = new java_cup.runtime.Symbol(12/*person*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // person ::= LECTURER 
            {
              People RESULT = null;
		 RESULT = People.LECTURER; 
              CUP$Tolk$result = new java_cup.runtime.Symbol(12/*person*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // labnotes ::= LABNOTES 
            {
              Things RESULT = null;
		 RESULT = Things.UNKNOWNLABNOTES; 
              CUP$Tolk$result = new java_cup.runtime.Symbol(9/*labnotes*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // labnotes ::= NUMME LABNOTES 
            {
              Things RESULT = null;
		 RESULT = Things.NUMMELABNOTES; 
              CUP$Tolk$result = new java_cup.runtime.Symbol(9/*labnotes*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // labnotes ::= PROGP LABNOTES 
            {
              Things RESULT = null;
		 RESULT = Things.PROGPLABNOTES; 
              CUP$Tolk$result = new java_cup.runtime.Symbol(9/*labnotes*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // book ::= BOOK 
            {
              Things RESULT = null;
		 RESULT = Things.UNKNOWNBOOK; 
              CUP$Tolk$result = new java_cup.runtime.Symbol(8/*book*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // book ::= PROLOG BOOK 
            {
              Things RESULT = null;
		 RESULT = Things.PROLOGBOOK;  
              CUP$Tolk$result = new java_cup.runtime.Symbol(8/*book*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // book ::= HASKELL BOOK 
            {
              Things RESULT = null;
		 RESULT = Things.HASKELLBOOK; 
              CUP$Tolk$result = new java_cup.runtime.Symbol(8/*book*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // thing ::= pen 
            {
              Things RESULT = null;
		int pleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right;
		Things p = (Things)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).value;
		 RESULT = p; 
              CUP$Tolk$result = new java_cup.runtime.Symbol(10/*thing*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // thing ::= labnotes 
            {
              Things RESULT = null;
		int nleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left;
		int nright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right;
		Things n = (Things)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).value;
		 RESULT = n; 
              CUP$Tolk$result = new java_cup.runtime.Symbol(10/*thing*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // thing ::= book 
            {
              Things RESULT = null;
		int bleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left;
		int bright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right;
		Things b = (Things)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).value;
		 RESULT = b; 
              CUP$Tolk$result = new java_cup.runtime.Symbol(10/*thing*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // talk_instr ::= SAY SOME_STRING TILL person 
            {
              Command RESULT = null;
		int sleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-2)).left;
		int sright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-2)).right;
		String s = (String)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-2)).value;
		int pleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left;
		int pright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right;
		People p = (People)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).value;
		 RESULT = new SayCommand(s, p); 
              CUP$Tolk$result = new java_cup.runtime.Symbol(6/*talk_instr*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-3)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // greet_instr ::= GREET person 
            {
              Command RESULT = null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right;
		People a = (People)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).value;
		 RESULT = new GreetCommand(a); 
              CUP$Tolk$result = new java_cup.runtime.Symbol(7/*greet_instr*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // go_instr ::= GO DIRECTION 
            {
              Command RESULT = null;
		int dleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left;
		int dright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right;
		Direction d = (Direction)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).value;
		 RESULT = new GoCommand(d); 
              CUP$Tolk$result = new java_cup.runtime.Symbol(5/*go_instr*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // drop_instr ::= DROP thing 
            {
              Command RESULT = null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right;
		Things t = (Things)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).value;
		 RESULT = new DropCommand(t); 
              CUP$Tolk$result = new java_cup.runtime.Symbol(4/*drop_instr*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // take_instr ::= TAKE thing 
            {
              Command RESULT = null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right;
		Things t = (Things)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).value;
		 RESULT = new TakeCommand(t); 
              CUP$Tolk$result = new java_cup.runtime.Symbol(3/*take_instr*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // one_instruction ::= BYEBYE 
            {
              Command RESULT = null;
		 RESULT = new QuitCommand(); 
              CUP$Tolk$result = new java_cup.runtime.Symbol(2/*one_instruction*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // one_instruction ::= greet_instr 
            {
              Command RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right;
		Command i = (Command)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).value;
		 RESULT = i; 
              CUP$Tolk$result = new java_cup.runtime.Symbol(2/*one_instruction*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // one_instruction ::= talk_instr 
            {
              Command RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right;
		Command i = (Command)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).value;
		 RESULT = i; 
              CUP$Tolk$result = new java_cup.runtime.Symbol(2/*one_instruction*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // one_instruction ::= go_instr 
            {
              Command RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right;
		Command i = (Command)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).value;
		 RESULT = i; 
              CUP$Tolk$result = new java_cup.runtime.Symbol(2/*one_instruction*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // one_instruction ::= drop_instr 
            {
              Command RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right;
		Command i = (Command)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).value;
		 RESULT = i; 
              CUP$Tolk$result = new java_cup.runtime.Symbol(2/*one_instruction*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // one_instruction ::= take_instr 
            {
              Command RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right;
		Command i = (Command)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).value;
		 RESULT = i; 
              CUP$Tolk$result = new java_cup.runtime.Symbol(2/*one_instruction*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // instruction ::= one_instruction PERIOD 
            {
              List RESULT = null;
		int ileft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).left;
		int iright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).right;
		Command i = (Command)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).value;
		 RESULT=new java.util.ArrayList(); RESULT.add(0,i); 
              CUP$Tolk$result = new java_cup.runtime.Symbol(1/*instruction*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          return CUP$Tolk$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= instruction EOF 
            {
              Object RESULT = null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).right;
		List start_val = (List)((java_cup.runtime.Symbol) CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).value;
		RESULT = start_val;
              CUP$Tolk$result = new java_cup.runtime.Symbol(0/*$START*/, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-1)).left, ((java_cup.runtime.Symbol)CUP$Tolk$stack.elementAt(CUP$Tolk$top-0)).right, RESULT);
            }
          /* ACCEPT */
          CUP$Tolk$parser.done_parsing();
          return CUP$Tolk$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

